from pathlib import Path
p=Path('recent-works-admin.js')
s=p.read_text(encoding='utf-8')

# Replace media manager markup with a clearer compact structure.
old='''    <section id="recentMediaManager" class="recent-media-manager" hidden>\n      <div class="recent-step-label recent-step-media"><span>2</span><div><strong>Fotos e vídeos</strong><small>Adicione as mídias, escolha a capa e organize a ordem</small></div></div>\n      <div class="recent-media-head"><div><h3>Mídias deste trabalho</h3><p id="recentMediaTitle">Selecione um trabalho para gerenciar suas fotos e vídeos.</p></div><button type="button" class="btn btn-ghost" id="recentMediaClose">Fechar</button></div>\n      <div class="recent-media-upload"><label class="btn btn-primary" for="recentMediaInput">Adicionar fotos ou vídeos</label><input id="recentMediaInput" type="file" accept="image/jpeg,image/png,image/webp,image/avif,video/mp4,video/webm" multiple><span id="recentMediaStatus" class="recent-status"></span></div>\n      <div id="recentMediaGrid" class="recent-media-grid"></div>\n    </section>'''
new='''    <section id="recentMediaManager" class="recent-media-manager" hidden>\n      <div class="recent-media-topbar">\n        <div class="recent-step-label recent-step-media"><span>2</span><div><strong>Fotos e vídeos</strong><small>Adicione as mídias, escolha a capa e organize a ordem</small></div></div>\n        <button type="button" class="btn btn-ghost recent-media-close" id="recentMediaClose">Fechar</button>\n      </div>\n      <div class="recent-media-context">\n        <span class="recent-media-context-label">Trabalho selecionado</span>\n        <strong id="recentMediaTitle">Selecione um trabalho para gerenciar suas fotos e vídeos.</strong>\n      </div>\n      <div class="recent-media-upload">\n        <label class="btn btn-primary recent-media-add" for="recentMediaInput"><span class="recent-media-add-icon">＋</span>Adicionar fotos ou vídeos</label>\n        <input id="recentMediaInput" type="file" accept="image/jpeg,image/png,image/webp,image/avif,video/mp4,video/webm" multiple>\n        <span class="recent-media-upload-help">JPG, PNG, WebP, AVIF, MP4 ou WebM</span>\n      </div>\n      <span id="recentMediaStatus" class="recent-status recent-media-status"></span>\n      <div id="recentMediaGrid" class="recent-media-grid"></div>\n    </section>'''
if old not in s:
    raise SystemExit('media manager markup block not found')
s=s.replace(old,new,1)

# Replace old media-manager CSS lines with the refined version.
old_css='''    .recent-media-manager{margin:22px 0 26px;padding:18px;border:1px solid rgba(201,162,75,.18);border-radius:14px;background:#0f0e0c}\n    .recent-media-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:14px}.recent-media-head h3{margin:0 0 4px;font-size:1.2rem}.recent-media-head p{margin:0;color:#a89d86;font-size:.8rem}\n    .recent-media-upload{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:14px}.recent-media-upload input{display:none}.recent-media-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.recent-media-card{border:1px solid rgba(201,162,75,.14);border-radius:12px;overflow:hidden;background:#12100d}.recent-media-card figure{margin:0;aspect-ratio:4/3;background:#070706}.recent-media-card img,.recent-media-card video{width:100%;height:100%;object-fit:cover}.recent-media-card-body{padding:9px;display:grid;gap:8px}.recent-media-card-body input{width:100%;background:#0e0d0b;border:1px solid rgba(201,162,75,.18);color:#f3ecdc;border-radius:8px;padding:8px}.recent-media-actions{display:flex;gap:6px;flex-wrap:wrap}.recent-media-actions .btn{padding:7px 9px;font-size:.72rem}.recent-cover-on{color:#e6c878;border-color:rgba(230,200,120,.5)!important}\n'''
new_css='''    .recent-media-manager{margin:22px 0 26px;padding:22px;border:1px solid rgba(201,162,75,.18);border-radius:16px;background:#0d0c0a}\n    .recent-media-topbar{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;margin-bottom:18px}.recent-step-media{margin:0}.recent-media-close{flex:0 0 auto;padding:8px 12px;font-size:.76rem}\n    .recent-media-context{display:grid;gap:5px;padding:14px 16px;margin-bottom:16px;border:1px solid rgba(201,162,75,.11);border-radius:12px;background:rgba(201,162,75,.025)}.recent-media-context-label{color:#817765;font-size:.65rem;text-transform:uppercase;letter-spacing:.12em}.recent-media-context strong{font-size:1rem;font-weight:500;color:#f3ecdc}\n    .recent-media-upload{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:8px}.recent-media-upload input{display:none}.recent-media-add{display:inline-flex;align-items:center;justify-content:center;gap:7px;width:auto;min-width:210px}.recent-media-add-icon{font-size:1rem;line-height:1}.recent-media-upload-help{color:#756d5d;font-size:.72rem}.recent-media-status{display:block;margin:6px 0 14px;min-height:18px}\n    .recent-media-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.recent-media-grid:empty{min-height:118px;border:1px dashed rgba(201,162,75,.15);border-radius:12px;display:grid;place-items:center}.recent-media-grid:empty:before{content:'Nenhuma mídia adicionada ainda.';color:#817765;font-size:.82rem}.recent-media-card{border:1px solid rgba(201,162,75,.14);border-radius:12px;overflow:hidden;background:#12100d}.recent-media-card figure{margin:0;aspect-ratio:4/3;background:#070706}.recent-media-card img,.recent-media-card video{width:100%;height:100%;object-fit:cover}.recent-media-card-body{padding:9px;display:grid;gap:8px}.recent-media-card-body input{width:100%;background:#0e0d0b;border:1px solid rgba(201,162,75,.18);color:#f3ecdc;border-radius:8px;padding:8px}.recent-media-actions{display:flex;gap:6px;flex-wrap:wrap}.recent-media-actions .btn{padding:7px 9px;font-size:.72rem}.recent-cover-on{color:#e6c878;border-color:rgba(230,200,120,.5)!important}\n'''
if old_css not in s:
    raise SystemExit('media manager css block not found')
s=s.replace(old_css,new_css,1)

# Improve responsive stacking for the media header and upload controls.
s=s.replace("    @media(max-width:760px){.recent-form{grid-template-columns:1fr}.recent-span-2{grid-column:auto}.recent-row{grid-template-columns:1fr}.recent-row-actions{justify-content:flex-start}.recent-admin{padding:20px}}",
            "    @media(max-width:760px){.recent-form{grid-template-columns:1fr}.recent-span-2{grid-column:auto}.recent-row{grid-template-columns:1fr}.recent-row-actions{justify-content:flex-start}.recent-admin{padding:20px}.recent-media-manager{padding:16px}.recent-media-topbar{align-items:stretch}.recent-media-add{width:100%}.recent-media-upload-help{width:100%}}",1)

p.write_text(s,encoding='utf-8')
