import { createClient, BetterAuthVanillaAdapter } from 'https://esm.sh/@neondatabase/neon-js@0.7.0-beta?bundle';

const AUTH_URL = 'https://ep-lucky-rice-axp36rxg.neonauth.c-4.us-east-2.aws.neon.tech/neondb/auth';
const DATA_API_URL = 'https://ep-lucky-rice-axp36rxg.apirest.c-4.us-east-2.aws.neon.tech/neondb/rest/v1';
const STORAGE_FN = 'https://br-gentle-water-axxtumld-siteimages.compute.c-4.us-east-2.aws.neon.tech/';
const MAX_IMAGE_BYTES = 25 * 1024 * 1024;
const MAX_VIDEO_BYTES = 100 * 1024 * 1024;

const neon = createClient({ auth: { adapter: BetterAuthVanillaAdapter(), url: AUTH_URL }, dataApi: { url: DATA_API_URL } });
const $ = id => document.getElementById(id);
const authView=$('authView'), panelView=$('panelView'), authMsg=$('authMsg'), libraryMsg=$('libraryMsg');
const loginForm=$('loginForm'), googleBtn=$('googleBtn'), logoutBtn=$('logoutBtn');
const uploadCategory=$('uploadCategory'), filterCategory=$('filterCategory'), uploadAlt=$('uploadAlt');
const fileInput=$('fileInput'), uploadBtn=$('uploadBtn'), uploadQueue=$('uploadQueue'), imageGrid=$('imageGrid'), dropzone=$('dropzone'), refreshBtn=$('refreshBtn');
let categories=[], selectedFiles=[], currentUser=null;

function setMsg(el,text='',type=''){el.textContent=text;el.className='msg'+(type?' '+type:'');}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function humanBytes(bytes){if(!bytes)return'—';if(bytes<1024*1024)return Math.round(bytes/1024)+' KB';return(bytes/1024/1024).toFixed(1)+' MB';}
function isVideoType(type){return /^video\//i.test(type||'');}
function validFile(f){return /^image\/(jpeg|png|webp|avif)$/i.test(f.type)?f.size<=MAX_IMAGE_BYTES:/^video\/(mp4|webm)$/i.test(f.type)&&f.size<=MAX_VIDEO_BYTES;}
async function getSession(){const r=await neon.auth.getSession();return r?.data||r||null;}
async function checkAdmin(){const {data,error}=await neon.from('site_admins').select('user_id,email').limit(1);return !error&&Array.isArray(data)&&data.length>0;}

async function boot(){try{const s=await getSession();if(!s?.user)return showAuth();currentUser=s.user;if(!(await checkAdmin())){await neon.auth.signOut();setMsg(authMsg,'Esta conta não tem acesso administrativo.','error');return showAuth();}await showPanel();}catch(e){console.error(e);setMsg(authMsg,'Não foi possível validar a sessão. Tente novamente.','error');showAuth();}}
function showAuth(){authView.hidden=false;panelView.hidden=true;}
async function showPanel(){authView.hidden=true;panelView.hidden=false;$('welcome').textContent=currentUser?.email||'';await loadCategories();await loadMedia();}

googleBtn.addEventListener('click',async()=>{setMsg(authMsg,'Abrindo o Google…');try{await neon.auth.signIn.social({provider:'google',callbackURL:location.origin+'/painel'});}catch(e){console.error(e);setMsg(authMsg,'Não foi possível iniciar o login com Google.','error');}});
loginForm.addEventListener('submit',async e=>{e.preventDefault();setMsg(authMsg,'Entrando…');try{const email=$('loginEmail').value.trim(),password=$('loginPassword').value;const r=await neon.auth.signIn.email({email,password});if(r?.error)throw new Error(r.error.message||'Credenciais inválidas.');const s=await getSession();currentUser=s?.user;if(!currentUser||!(await checkAdmin())){await neon.auth.signOut();throw new Error('Esta conta não tem acesso administrativo.');}setMsg(authMsg,'');await showPanel();}catch(err){setMsg(authMsg,err?.message||'Não foi possível entrar.','error');}});
logoutBtn.addEventListener('click',async()=>{await neon.auth.signOut();currentUser=null;showAuth();});

async function loadCategories(){const {data,error}=await neon.from('site_categories').select('slug,label,area,sort_order').order('sort_order',{ascending:true});if(error)throw error;categories=data||[];uploadCategory.innerHTML=categories.map(c=>`<option value="${esc(c.slug)}">${esc(c.label)}</option>`).join('');filterCategory.innerHTML='<option value="">Todas as categorias</option>'+categories.map(c=>`<option value="${esc(c.slug)}">${esc(c.label)}</option>`).join('');}
function categoryLabel(slug){return categories.find(c=>c.slug===slug)?.label||slug;}
fileInput.addEventListener('change',()=>setFiles([...fileInput.files]));
['dragenter','dragover'].forEach(t=>dropzone.addEventListener(t,e=>{e.preventDefault();dropzone.classList.add('drag');}));
['dragleave','drop'].forEach(t=>dropzone.addEventListener(t,e=>{e.preventDefault();dropzone.classList.remove('drag');}));
dropzone.addEventListener('drop',e=>setFiles([...e.dataTransfer.files]));
function setFiles(files){selectedFiles=files.filter(validFile);uploadBtn.disabled=!selectedFiles.length;uploadQueue.innerHTML=selectedFiles.length?selectedFiles.map(f=>`<div class="queue-item"><span>${isVideoType(f.type)?'Vídeo · ':''}${esc(f.name)}</span><span>${humanBytes(f.size)}</span></div>`).join(''):'<div class="queue-item"><span>Nenhuma mídia válida selecionada.</span><span></span></div>';}
async function optimizeImage(file){if(isVideoType(file.type)||file.type==='image/avif')return file;const bitmap=await createImageBitmap(file),maxSide=2400,scale=Math.min(1,maxSide/Math.max(bitmap.width,bitmap.height)),width=Math.max(1,Math.round(bitmap.width*scale)),height=Math.max(1,Math.round(bitmap.height*scale));const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;canvas.getContext('2d',{alpha:true}).drawImage(bitmap,0,0,width,height);bitmap.close();const blob=await new Promise(r=>canvas.toBlob(r,'image/webp',.88));return blob?new File([blob],file.name.replace(/\.[^.]+$/,'')+'.webp',{type:'image/webp'}):file;}
async function storageCall(payload){const token=await neon.auth.getJWTToken?.();if(!token)throw new Error('Sessão expirada. Entre novamente.');const res=await fetch(STORAGE_FN,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(payload)});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Falha no armazenamento.');return data;}

uploadBtn.addEventListener('click',async()=>{if(!selectedFiles.length)return;uploadBtn.disabled=true;const category=uploadCategory.value,alt=uploadAlt.value.trim();let done=0;setMsg(libraryMsg,'');try{for(const original of selectedFiles){const file=await optimizeImage(original);uploadBtn.textContent=`Enviando ${done+1} de ${selectedFiles.length}…`;const signed=await storageCall({action:'presign',category,fileName:file.name,contentType:file.type});const put=await fetch(signed.uploadUrl,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!put.ok)throw new Error('O arquivo não pôde ser enviado.');const {error}=await neon.from('site_images').insert({storage_key:signed.storageKey,public_url:signed.publicUrl,category,alt_text:alt,sort_order:Date.now()+done,is_visible:true,is_cover:false,mime_type:file.type,bytes:file.size,created_by:currentUser?.id||null});if(error){await storageCall({action:'delete',storageKey:signed.storageKey}).catch(()=>{});throw error;}done++;}setMsg(libraryMsg,`${done} arquivo${done===1?'':'s'} enviado${done===1?'':'s'} com sucesso.`,'success');selectedFiles=[];fileInput.value='';uploadQueue.innerHTML='';uploadAlt.value='';await loadMedia();}catch(err){console.error(err);setMsg(libraryMsg,err?.message||'Não foi possível concluir o envio.','error');}finally{uploadBtn.textContent='Enviar selecionadas';uploadBtn.disabled=!selectedFiles.length;}});
filterCategory.addEventListener('change',loadMedia);refreshBtn.addEventListener('click',loadMedia);
async function loadMedia(){imageGrid.innerHTML='<div class="empty">Carregando…</div>';let q=neon.from('site_images').select('*').order('category',{ascending:true}).order('sort_order',{ascending:true});if(filterCategory.value)q=q.eq('category',filterCategory.value);const {data,error}=await q;if(error){console.error(error);imageGrid.innerHTML='<div class="empty">Não foi possível carregar a biblioteca.</div>';return;}renderMedia(data||[]);}
function renderMedia(items){if(!items.length){imageGrid.innerHTML='<div class="empty">Ainda não há mídias nesta categoria.</div>';return;}imageGrid.innerHTML=items.map(m=>{const video=isVideoType(m.mime_type);const preview=video?`<video src="${esc(m.public_url)}" controls preload="metadata"></video>`:`<img src="${esc(m.public_url)}" alt="${esc(m.alt_text||categoryLabel(m.category))}" loading="lazy">`;return `<article class="photo-card" data-id="${esc(m.id)}" data-key="${esc(m.storage_key)}"><figure>${preview}</figure><div class="photo-body"><div class="photo-meta"><span>${video?'Vídeo · ':''}${esc(categoryLabel(m.category))}</span><span>${humanBytes(Number(m.bytes||0))}</span></div><div class="photo-row"><select class="card-category" aria-label="Categoria">${categories.map(c=>`<option value="${esc(c.slug)}" ${c.slug===m.category?'selected':''}>${esc(c.label)}</option>`).join('')}</select><input class="card-order" type="number" value="${Number(m.sort_order||0)}" aria-label="Ordem"></div><input class="card-alt" type="text" maxlength="180" value="${esc(m.alt_text||'')}" placeholder="Texto alternativo"><div class="toggles"><label><input class="card-visible" type="checkbox" ${m.is_visible?'checked':''}> Publicada</label><label><input class="card-cover" type="checkbox" ${m.is_cover?'checked':''} ${video?'disabled title="Vídeos não podem ser capa"':''}> Capa</label></div><div class="card-actions"><button type="button" class="btn save-btn">Salvar</button><button type="button" class="btn btn-danger delete-btn">Excluir</button></div></div></article>`;}).join('');imageGrid.querySelectorAll('.photo-card').forEach(card=>{card.querySelector('.save-btn').addEventListener('click',()=>saveCard(card));card.querySelector('.delete-btn').addEventListener('click',()=>deleteCard(card));});}
async function saveCard(card){const id=card.dataset.id,category=card.querySelector('.card-category').value,isCover=card.querySelector('.card-cover').checked,payload={category,sort_order:Number(card.querySelector('.card-order').value||0),alt_text:card.querySelector('.card-alt').value.trim(),is_visible:card.querySelector('.card-visible').checked,is_cover:isCover};const btn=card.querySelector('.save-btn');btn.disabled=true;btn.textContent='Salvando…';try{if(isCover){const {error:e}=await neon.from('site_images').update({is_cover:false}).eq('category',category).neq('id',id);if(e)throw e;}const {error}=await neon.from('site_images').update(payload).eq('id',id);if(error)throw error;setMsg(libraryMsg,'Alterações salvas.','success');await loadMedia();}catch(e){console.error(e);setMsg(libraryMsg,'Não foi possível salvar esta mídia.','error');}finally{btn.disabled=false;btn.textContent='Salvar';}}
async function deleteCard(card){if(!confirm('Excluir esta mídia da biblioteca e do site?'))return;const id=card.dataset.id,key=card.dataset.key,btn=card.querySelector('.delete-btn');btn.disabled=true;btn.textContent='Excluindo…';try{const {error}=await neon.from('site_images').delete().eq('id',id);if(error)throw error;if(!key.startsWith('legacy:'))await storageCall({action:'delete',storageKey:key});card.remove();setMsg(libraryMsg,'Mídia excluída.','success');if(!imageGrid.querySelector('.photo-card'))imageGrid.innerHTML='<div class="empty">Ainda não há mídias nesta categoria.</div>';}catch(e){console.error(e);setMsg(libraryMsg,'Não foi possível excluir esta mídia.','error');btn.disabled=false;btn.textContent='Excluir';}}
boot();
